Repository praw-dev/praw, pull requests merged in 2020-05, with the labels that each got.

#1471 Reword documentation
  docs/getting_started/configuration/environment_variables.rst
Labels: Documentation, Minor Change

#1472 Add entries about ratelimit_seconds and timeout
  docs/getting_started/configuration/options.rst
Labels: Documentation

#1473 Change code style to match black's style
  praw/models/auth.py
  praw/models/comment_forest.py
  praw/models/helpers.py
  praw/models/inbox.py
  praw/models/listing/mixins/base.py
  praw/models/listing/mixins/gilded.py
  praw/models/listing/mixins/redditor.py
  praw/models/listing/mixins/rising.py
  praw/models/listing/mixins/submission.py
  praw/models/listing/mixins/subreddit.py
  praw/models/preferences.py
  praw/models/reddit/collections.py
  praw/models/reddit/comment.py
  praw/models/reddit/emoji.py
  praw/models/reddit/live.py
  praw/models/reddit/mixins/__init__.py
  praw/models/reddit/mixins/editable.py
  praw/models/reddit/mixins/gildable.py
  praw/models/reddit/mixins/inboxable.py
  praw/models/reddit/mixins/inboxtoggleable.py
  praw/models/reddit/mixins/messageable.py
  praw/models/reddit/mixins/replyable.py
  praw/models/reddit/mixins/reportable.py
  praw/models/reddit/mixins/savable.py
  praw/models/reddit/mixins/votable.py
  praw/models/reddit/modmail.py
  praw/models/reddit/more.py
  praw/models/reddit/multi.py
  praw/models/reddit/poll.py
  praw/models/reddit/redditor.py
  praw/models/reddit/removal_reasons.py
  praw/models/reddit/rules.py
  praw/models/reddit/submission.py
  praw/models/reddit/subreddit.py
  praw/models/reddit/widgets.py
  praw/models/reddit/wikipage.py
  praw/models/user.py
  praw/models/util.py
  praw/reddit.py
Labels: Documentation

#1474 Make more black-esque formatting changes
  CHANGES.rst
  README.rst
  docs/getting_started/authentication.rst
  docs/getting_started/configuration.rst
  docs/getting_started/configuration/options.rst
  docs/getting_started/configuration/prawini.rst
  docs/getting_started/configuration/reddit_initialization.rst
  docs/getting_started/quick_start.rst
  docs/tutorials/comments.rst
  docs/tutorials/reply_bot.rst
  praw/models/comment_forest.py
  praw/models/inbox.py
  praw/models/listing/mixins/base.py
  praw/models/listing/mixins/redditor.py
  praw/models/reddit/collections.py
  praw/models/reddit/live.py
  praw/models/reddit/mixins/messageable.py
  praw/models/reddit/subreddit.py
  praw/models/reddit/widgets.py
  praw/models/reddit/wikipage.py
Labels: Documentation

#1478 Document the `reason` parameter in SubredditStylesheet.update method
  praw/models/reddit/subreddit.py
Labels: Documentation, Minor Change

#1488 Apply post-merge code review suggestions and update documentation
  praw/models/reddit/rules.py
  praw/models/reddit/subreddit.py
  tests/integration/models/reddit/test_rules.py
  tests/unit/test_deprecations.py
Labels: Documentation

#1489 Add deprecation directive
  docs/package_info/praw7_migration.rst
  praw/exceptions.py
  praw/reddit.py
Labels: Documentation, Minor Change

#1490 Remove all TypeVars
  praw/exceptions.py
  praw/models/base.py
  praw/models/comment_forest.py
  praw/models/front.py
  praw/models/inbox.py
  praw/models/list/base.py
  praw/models/listing/domain.py
  praw/models/listing/generator.py
  praw/models/listing/mixins/redditor.py
  praw/models/listing/mixins/rising.py
  praw/models/listing/mixins/submission.py
  praw/models/listing/mixins/subreddit.py
  praw/models/mod_action.py
  praw/models/preferences.py
  praw/models/reddit/base.py
  praw/models/reddit/collections.py
  praw/models/reddit/comment.py
  praw/models/reddit/emoji.py
  praw/models/reddit/live.py
  praw/models/reddit/message.py
  praw/models/reddit/mixins/messageable.py
  praw/models/reddit/modmail.py
  praw/models/reddit/more.py
  praw/models/reddit/multi.py
  praw/models/reddit/poll.py
  praw/models/reddit/redditor.py
  praw/models/reddit/removal_reasons.py
  praw/models/reddit/rules.py
  praw/models/reddit/submission.py
  praw/models/reddit/subreddit.py
  praw/models/reddit/wikipage.py
  praw/models/redditors.py
  praw/models/trophy.py
  praw/models/user.py
  praw/objector.py
  tests/integration/models/reddit/test_rules.py
  tests/integration/test_reddit.py
  tests/unit/models/reddit/test_rules.py
Labels: Documentation

#1498 Minor correction
  praw/models/reddit/redditor.py
Labels: Documentation, Minor Change

#1454 Update Removal Reasons
  CHANGES.rst
  praw/models/reddit/removal_reasons.py
  tests/integration/cassettes/TestSubredditRemovalReasons.test_update_empty.json
  tests/integration/models/reddit/test_removal_reasons.py
  tests/unit/models/reddit/test_removal_reasons.py
Labels: Documentation, Feature

#1501 Bugfix: Correct error message when we fail to fetch a comment
  praw/models/reddit/comment.py
Labels: Bug

#1505 Revert "Remove build directory"
  .github/workflows/ci.yml
Labels: Developer Environment, Minor Change

#1507 Add FAQ entry per #880
  docs/getting_started/faq.rst
Labels: Documentation
