Repository praw-dev/praw, pull requests merged in 2020-04, with the labels that each got.

#1387 Subreddit update
  praw/models/reddit/subreddit.py
  tests/integration/cassettes/TestSubredditModeration.test_update.json
  tests/integration/models/reddit/test_subreddit.py
Labels: Documentation

#1389 Update pre_push.py
  pre_push.py
Labels: Bug

#1394 Fix documentation that contained invalid code
  README.rst
Labels: Documentation, Minor Change

#1392 Comment clarification
  AUTHORS.rst
  praw/models/reddit/comment.py
  praw/models/reddit/message.py
  praw/models/redditors.py
Labels: Documentation, Minor Change

#1396 Documentation: wrong prefix
  praw/models/reddit/comment.py
Labels: Documentation, Minor Change

#1397 Add line numbers to any missed statements
  .github/workflows/ci.yml
Labels: Developer Environment, Feature, Minor Change

#1382 Start a glossary
  docs/index.rst
  docs/package_info/glossary.rst
Labels: Documentation

#1406 Minor Documentation Improvements
  CHANGES.rst
  docs/getting_started/configuration.rst
  docs/getting_started/installation.rst
  docs/package_info/contributing.rst
  docs/tutorials/reply_bot.rst
Labels: Documentation, Minor Change

#1408 Update prawini.rst
  docs/getting_started/configuration/prawini.rst
Labels: Documentation, Minor Change

#1409 Use unittest.mock over mock package
  setup.py
  tests/integration/models/reddit/test_collections.py
  tests/integration/models/reddit/test_comment.py
  tests/integration/models/reddit/test_emoji.py
  tests/integration/models/reddit/test_live.py
  tests/integration/models/reddit/test_message.py
  tests/integration/models/reddit/test_modmail.py
  tests/integration/models/reddit/test_multi.py
  tests/integration/models/reddit/test_redditor.py
  tests/integration/models/reddit/test_removal_reasons.py
  tests/integration/models/reddit/test_submission.py
  tests/integration/models/reddit/test_subreddit.py
  tests/integration/models/reddit/test_widgets.py
  tests/integration/models/reddit/test_wikipage.py
  tests/integration/models/test_comment_forest.py
  tests/integration/models/test_inbox.py
  tests/integration/models/test_preferences.py
  tests/integration/models/test_redditors.py
  tests/integration/models/test_subreddits.py
  tests/integration/models/test_trophy.py
  tests/integration/models/test_user.py
  tests/integration/test_reddit.py
  tests/unit/models/test_redditors.py
  tests/unit/test_config.py
  tests/unit/test_reddit.py
Labels: Developer Environment, Minor Change

#1410 Forgot to close parenthesis
  docs/getting_started/configuration/prawini.rst
Labels: Documentation, Minor Change

#1388 Fix bug in SubredditFlair update method
  AUTHORS.rst
  CHANGES.rst
  praw/models/reddit/subreddit.py
  tests/integration/cassettes/TestSubredditFlair.test_update_quotes.json
  tests/integration/models/reddit/test_subreddit.py
Labels: Bug, Minor Change

#1413 Fix rendering typo
  docs/package_info/glossary.rst
Labels: Documentation, Minor Change

#1411 Add note to install the [dev] options
  docs/package_info/contributing.rst
Labels: Documentation, Minor Change

#1414 Support PRAW5 per #1412
  SECURITY.md
Labels: Documentation, Minor Change

#1417 Type all mixins
  praw/models/reddit/mixins/editable.py
  praw/models/reddit/mixins/fullname.py
  praw/models/reddit/mixins/messageable.py
  praw/models/reddit/mixins/replyable.py
  praw/models/reddit/mixins/reportable.py
  praw/models/reddit/mixins/savable.py
  praw/models/reddit/mixins/votable.py
Labels: Developer Environment, Documentation, Minor Change

#1419 Use seealso:: directive
  praw/models/listing/mixins/submission.py
  praw/models/reddit/collections.py
  praw/models/reddit/mixins/__init__.py
  praw/models/reddit/mixins/inboxable.py
  praw/models/reddit/mixins/inboxtoggleable.py
  praw/models/reddit/mixins/savable.py
  praw/models/reddit/mixins/votable.py
  praw/models/reddit/submission.py
Labels: Documentation, Minor Change

#1422 Convert timeout to int
  praw/config.py
  tests/unit/test_reddit.py
Labels: Bug, Critical, Minor Change

#1398 Api ratelimit
  CHANGES.rst
  praw/config.py
  praw/praw.ini
  praw/reddit.py
  tests/unit/test_reddit.py
Labels: Feature

#1420 Fix multitude of typos
  docs/getting_started/quick_start.rst
  docs/package_info/references.rst
  docs/tutorials/comments.rst
  praw/models/auth.py
  praw/models/comment_forest.py
  praw/models/helpers.py
  praw/models/listing/mixins/base.py
  praw/models/preferences.py
  praw/models/reddit/emoji.py
  praw/models/reddit/live.py
  praw/models/reddit/mixins/__init__.py
  praw/models/reddit/multi.py
  praw/models/reddit/redditor.py
  praw/models/reddit/removal_reasons.py
  praw/models/reddit/submission.py
  praw/models/reddit/subreddit.py
  praw/models/reddit/widgets.py
  praw/models/reddit/wikipage.py
  praw/models/redditors.py
  praw/models/subreddits.py
  praw/models/trophy.py
  praw/models/user.py
  praw/reddit.py
Labels: Documentation

#1426 Run isort utility
  praw/models/reddit/mixins/messageable.py
  praw/models/reddit/mixins/savable.py
  tests/conftest.py
  tests/integration/models/reddit/test_collections.py
  tests/integration/models/reddit/test_comment.py
  tests/integration/models/reddit/test_emoji.py
  tests/integration/models/reddit/test_live.py
  tests/integration/models/reddit/test_message.py
  tests/integration/models/reddit/test_multi.py
  tests/integration/models/reddit/test_redditor.py
  tests/integration/models/reddit/test_removal_reasons.py
  tests/integration/models/reddit/test_submission.py
  tests/integration/models/reddit/test_subreddit.py
  tests/integration/models/reddit/test_widgets.py
  tests/integration/models/reddit/test_wikipage.py
  tests/integration/models/test_comment_forest.py
  tests/integration/models/test_inbox.py
  tests/integration/models/test_user.py
  tests/unit/test_config.py
  tests/unit/test_reddit.py
Labels: Developer Environment, Minor Change

#1449 Revert "Get rid of redundant ``'<content>'``"
  praw/models/helpers.py
  praw/models/preferences.py
  praw/models/reddit/emoji.py
  praw/models/reddit/live.py
  praw/models/reddit/multi.py
  praw/models/reddit/removal_reasons.py
  praw/models/reddit/subreddit.py
  praw/models/reddit/widgets.py
  praw/models/reddit/wikipage.py
  praw/models/trophy.py
Labels: Documentation, Minor Change

#1453 Change to report via stderr
  docs/getting_started/configuration/options.rst
  setup.py
Labels: Documentation, Minor Change

#1450 Add FAQ entry about login
  docs/getting_started/faq.rst
Labels: Documentation, Minor Change

#1446 Update phrasing about comprehensiveness of documented attributes
  praw/models/reddit/comment.py
  praw/models/reddit/live.py
  praw/models/reddit/message.py
  praw/models/reddit/modmail.py
  praw/models/reddit/multi.py
  praw/models/reddit/redditor.py
  praw/models/reddit/removal_reasons.py
  praw/models/reddit/submission.py
  praw/models/reddit/subreddit.py
  praw/models/reddit/widgets.py
  praw/models/reddit/wikipage.py
  praw/models/stylesheet.py
  praw/models/trophy.py
Labels: Documentation, Minor Change

#1441 Set minimum python version to >3.5.3
  setup.py
Labels: Critical, Delay until next release, Minor Change

#1457 Remove build directory
  .github/workflows/ci.yml
Labels: Developer Environment

#1455 Add json parameter for POST, PATCH, and PUT
  praw/reddit.py
  tests/unit/test_reddit.py
Labels: Feature, Minor Change

#1461 Update `update`
  CHANGES.rst
  praw/endpoints.py
  praw/models/reddit/subreddit.py
  tests/integration/cassettes/TestSubredditModeration.test_update.json
Labels: Bug

#1444 Add rules class
  CHANGES.rst
  docs/code_overview/other.rst
  docs/code_overview/other/rule.rst
  docs/code_overview/other/rulemoderation.rst
  docs/code_overview/other/subredditrules.rst
  docs/code_overview/other/subredditrulesmoderation.rst
  praw/endpoints.py
  praw/models/__init__.py
  praw/models/reddit/rules.py
  praw/models/reddit/subreddit.py
  praw/objector.py
  praw/reddit.py
  tests/integration/cassettes/TestRule.test_add_rule.json
  tests/integration/cassettes/TestRule.test_add_rule_without_violation_reason.json
  tests/integration/cassettes/TestRule.test_delete_rule.json
  tests/integration/cassettes/TestRule.test_iter_rules.json
  tests/integration/cassettes/TestRule.test_reorder_rules.json
  tests/integration/cassettes/TestRule.test_reorder_rules_double.json
  tests/integration/cassettes/TestRule.test_reorder_rules_empty.json
  tests/integration/cassettes/TestRule.test_reorder_rules_no_reorder.json
  tests/integration/cassettes/TestRule.test_reorder_rules_omit.json
  tests/integration/cassettes/TestRule.test_update_rule.json
  tests/integration/cassettes/TestRule.test_update_rule_no_params.json
  tests/integration/cassettes/TestRule.test_update_rule_short_name.json
  tests/integration/cassettes/TestSubreddit.test_rules.json
  tests/integration/models/reddit/test_rules.py
  tests/integration/models/reddit/test_subreddit.py
  tests/unit/models/reddit/test_rules.py
  tests/unit/test_deprecations.py
Labels: Feature

#1460 Add support for submitting and viewing polls.
  CHANGES.rst
  docs/code_overview/other.rst
  docs/code_overview/other/poll.rst
  praw/endpoints.py
  praw/models/__init__.py
  praw/models/reddit/poll.py
  praw/models/reddit/submission.py
  praw/models/reddit/subreddit.py
  praw/objector.py
  tests/integration/cassettes/TestPollData.test_get_attrs.json
  tests/integration/cassettes/TestPollData.test_get_user_selection.json
  tests/integration/cassettes/TestSubreddit.test_submit_poll.json
  tests/integration/cassettes/TestSubreddit.test_submit_poll__flair.json
  tests/integration/cassettes/TestSubreddit.test_submit_poll__live_chat.json
  tests/integration/models/reddit/test_poll.py
  tests/integration/models/reddit/test_subreddit.py
  tests/unit/models/reddit/test_poll.py
Labels: Feature

#1462 Rename PollData.get_option to PollData.option; use split rather than partition
  praw/models/reddit/poll.py
  praw/objector.py
  tests/integration/models/reddit/test_poll.py
Labels: Feature, Minor Change

#1436 Add actual network-requesting test
  .github/workflows/ci.yml
  tests/integration/test_github_actions.py
Labels: Minor Change

#1463 Maintain compatibility with old rules
  praw/models/reddit/rules.py
  tests/integration/cassettes/TestRule.test_call.json
  tests/integration/models/reddit/test_rules.py
Labels: Minor Change

#1464 Skip if not in praw-dev/praw repo
  tests/integration/test_github_actions.py
Labels: Developer Environment, Minor Change

#1430 Add new log data
  docs/getting_started/logging.rst
Labels: Documentation, Minor Change

#1465 Directly test for the presence of the needed variables
  tests/integration/test_github_actions.py
Labels: Developer Environment, Minor Change

#1466 Add setup.py changes to tox.ini
  tox.ini
Labels: Developer Environment, Minor Change

#1431 Ensure that BadRequests without detailed error data are raised as actual BadRequests
  CHANGES.rst
  praw/reddit.py
  tests/integration/cassettes/TestReddit.test_bare_badrequest.json
  tests/integration/test_reddit.py
Labels: Bug, Minor Change

#1467 NETWORK_TEST env variable no longer needed
  .github/workflows/ci.yml
Labels: Developer Environment, Minor Change

#1469 Minor improvements to Rules
  praw/models/reddit/rules.py
Labels: Minor Change
