Repository praw-dev/praw, pull requests merged in 2020-06, with the labels that each got.

#1511 Add streams to live threads
  CHANGES.rst
  docs/code_overview/other.rst
  docs/code_overview/other/livethreadstream.rst
  praw/models/reddit/live.py
  tests/integration/cassettes/TestLiveThreadStream.test_updates.json
  tests/integration/models/reddit/test_live.py
Labels: Feature

#1514 Fix uncached properties
  praw/exceptions.py
  praw/models/reddit/comment.py
  praw/models/reddit/message.py
  praw/models/reddit/redditor.py
  praw/models/reddit/submission.py
  praw/models/reddit/subreddit.py
  praw/models/reddit/widgets.py
  praw/reddit.py
Labels: Documentation, Minor Change

#1434 Raise exception when invalid media is used
  CHANGES.rst
  praw/exceptions.py
  praw/models/reddit/subreddit.py
  tests/unit/models/reddit/test_subreddit.py
  tests/unit/test_deprecations.py
  tests/unit/test_exceptions.py
Labels: Bug

#1525 Apply black formatting
  tests/unit/models/reddit/test_subreddit.py
Labels: Developer Environment

#1531 Update subreddits/gold endpoint
  CHANGES.rst
  praw/endpoints.py
  praw/models/subreddits.py
  tests/integration/cassettes/TestSubreddits.test_gold__without_gold.json
  tests/integration/cassettes/TestSubreddits.test_premium__with_premium.json
  tests/integration/cassettes/TestSubreddits.test_premium__without_premium.json
  tests/integration/models/test_subreddits.py
  tests/unit/test_deprecations.py
Labels: Bug, Reddit API Change
