Repository praw-dev/praw, pull requests merged in 2020-10, with the labels that each got.

#1560 Add support for gallery urls
  CHANGES.rst
  praw/models/reddit/submission.py
  tests/unit/models/reddit/test_submission.py
Labels: Feature

#1561 Add invited moderators endpoint
  CHANGES.rst
  praw/endpoints.py
  praw/models/__init__.py
  praw/models/listing/listing.py
  praw/models/reddit/subreddit.py
  praw/objector.py
  praw/reddit.py
  tests/integration/cassettes/TestSubredditRelationships.test_moderator_invited_moderators.json
  tests/integration/models/reddit/test_subreddit.py
Labels: Feature

#1567 Add ability to award new awards
  CHANGES.rst
  docs/code_overview/models/awards.txt
  praw/endpoints.py
  praw/models/reddit/mixins/gildable.py
  praw/objector.py
  tests/integration/cassettes/TestComment.test_award.json
  tests/integration/cassettes/TestComment.test_award__not_enough_coins.json
  tests/integration/cassettes/TestComment.test_award__self_gild.json
  tests/integration/cassettes/TestComment.test_gild__no_creddits.json
  tests/integration/cassettes/TestSubmission.test_award.json
  tests/integration/cassettes/TestSubmission.test_award__not_enough_coins.json
  tests/integration/cassettes/TestSubmission.test_award__self_gild.json
  tests/integration/cassettes/TestSubmission.test_gild__no_creddits.json
  tests/integration/models/reddit/test_comment.py
  tests/integration/models/reddit/test_submission.py
  tests/unit/test_deprecations.py
  tools/check_docstring.py
  tools/check_documentation.py
  tools/generate_award_table.py
Labels: Feature

#1563 Add ability to submit selftext with inline media
  docs/code_overview/other.rst
  docs/code_overview/other/inlinegif.rst
  docs/code_overview/other/inlineimage.rst
  docs/code_overview/other/inlinemedia.rst
  docs/code_overview/other/inlinevideo.rst
  praw/endpoints.py
  praw/models/__init__.py
  praw/models/reddit/inline_media.py
  praw/models/reddit/subreddit.py
  tests/integration/cassettes/TestSubreddit.test_submit__selftext_inline_media.json
  tests/integration/models/reddit/test_subreddit.py
  tests/unit/models/reddit/test_inline_media.py
  tests/unit/models/reddit/test_subreddit.py
Labels: Feature

#1566 Fix modmail stream doc reference to "messages"
  praw/models/reddit/subreddit.py
Labels: Documentation

#1554 Make comment more descriptive
  praw/praw.ini
Labels: Minor Change
