Repository praw-dev/praw, pull requests merged in 2020-03, with the labels that each got.

#1361 Create an error that gets thrown if media is too large
  CHANGES.rst
  praw/exceptions.py
  praw/models/reddit/subreddit.py
  tests/integration/cassettes/TestSubreddit.test_submit_image__large.json
  tests/integration/models/reddit/test_subreddit.py
Labels: Feature

#1362 Fix code rendering in FAQ
  docs/getting_started/faq.rst
Labels: Documentation

#1333 Remove moderator_subreddits as per deprecation plan
  CHANGES.rst
  praw/models/user.py
  tests/integration/models/test_user.py
Labels: Delay until next release

#1345 New exception
  CHANGES.rst
  docs/index.rst
  docs/package_info/praw7_migration.rst
  praw/exceptions.py
  praw/models/reddit/live.py
  praw/models/reddit/mixins/reportable.py
  praw/models/reddit/subreddit.py
  praw/objector.py
  pytest.ini
  tests/integration/models/reddit/test_live.py
  tests/integration/models/reddit/test_subreddit.py
  tests/integration/test_objector.py
  tests/unit/test_deprecations.py
  tests/unit/test_exceptions.py
  tests/unit/test_objector.py
Labels: Feature

#1365 Raise RedditAPIException instead of BadRequest
  .flake8
  CHANGES.rst
  praw/models/reddit/mixins/__init__.py
  praw/models/reddit/redditor.py
  praw/models/user.py
  praw/reddit.py
  tests/integration/cassettes/TestCommentModeration.test_send_removal_message__error.json
  tests/integration/models/reddit/test_comment.py
  tests/integration/models/reddit/test_redditor.py
  tests/integration/models/reddit/test_submission.py
  tests/integration/models/test_user.py
  tests/unit/test_reddit.py
Labels: Feature

#1367 Add discussion_type parameter to subreddit.submit[_image,_video] methods
  AUTHORS.rst
  CHANGES.rst
  praw/models/reddit/subreddit.py
  tests/integration/cassettes/TestSubreddit.test_submit_image_chat.json
  tests/integration/cassettes/TestSubreddit.test_submit_live_chat.json
  tests/integration/cassettes/TestSubreddit.test_submit_video_chat.json
  tests/integration/models/reddit/test_subreddit.py
Labels: Feature

#1368 Change exceptions to use `issubclass` which does not require instantiation
  tests/unit/test_exceptions.py
Labels: Feature

#1372 Make comparable with other
  praw/models/reddit/emoji.py
  praw/models/reddit/more.py
  praw/models/reddit/wikipage.py
  tests/unit/models/reddit/test_emoji.py
  tests/unit/models/reddit/test_more.py
Labels: Feature

#1369 Make trophies comparable
  praw/models/trophy.py
  tests/integration/cassettes/TestTrophy.test_equality.json
  tests/integration/models/test_trophy.py
  tests/unit/models/test_trophy.py
Labels: Feature
