Repository praw-dev/praw, pull requests merged in 2020-02, with the labels that each got.

#1332 Add note for methods
  praw/models/reddit/subreddit.py
  praw/models/user.py
Labels: Documentation

#1337 Fix indentation on documentation
  docs/getting_started/authentication.rst
Labels: Documentation

#1312 Check documentation for example attributes and code examples
  .github/workflows/ci.yml
  pre_push.py
  tools/check_documentation.py
Labels: Documentation, Feature

#1307 Make SubredditFlairTemplates.update get previous flair information
  CHANGES.rst
  praw/exceptions.py
  praw/models/reddit/subreddit.py
  tests/integration/cassettes/TestSubredditFlairTemplates.test_update.json
  tests/integration/cassettes/TestSubredditFlairTemplates.test_update_false.json
  tests/integration/cassettes/TestSubredditFlairTemplates.test_update_fetch.json
  tests/integration/cassettes/TestSubredditFlairTemplates.test_update_fetch_no_css_class.json
  tests/integration/cassettes/TestSubredditFlairTemplates.test_update_fetch_no_text.json
  tests/integration/cassettes/TestSubredditFlairTemplates.test_update_fetch_no_text_or_css_class.json
  tests/integration/cassettes/TestSubredditFlairTemplates.test_update_fetch_only.json
  tests/integration/cassettes/TestSubredditFlairTemplates.test_update_invalid.json
  tests/integration/models/reddit/test_subreddit.py
  tests/unit/models/reddit/test_subreddit.py
  tests/unit/test_exceptions.py
Labels: Feature
