Repository praw-dev/praw, pull requests merged in 2020-01, with the labels that each got.

#1233 Allow use of refresh token instead of username/password in tests
  docs/package_info/contributing.rst
  tests/conftest.py
  tests/integration/__init__.py
Labels: Feature

#1051 Moderation streams
  CHANGES.rst
  docs/code_overview/other.rst
  docs/code_overview/other/subredditmoderationstream.rst
  praw/models/reddit/subreddit.py
  praw/models/util.py
  tests/conftest.py
  tests/integration/cassettes/TestSubredditModerationStreams.test_edited.json
  tests/integration/cassettes/TestSubredditModerationStreams.test_log.json
  tests/integration/cassettes/TestSubredditModerationStreams.test_modmail_conversations.json
  tests/integration/cassettes/TestSubredditModerationStreams.test_modqueue.json
  tests/integration/cassettes/TestSubredditModerationStreams.test_reports.json
  tests/integration/cassettes/TestSubredditModerationStreams.test_spam.json
  tests/integration/cassettes/TestSubredditModerationStreams.test_unmoderated.json
  tests/integration/cassettes/TestSubredditModerationStreams.test_unread.json
  tests/integration/models/reddit/test_subreddit.py
  tests/unit/models/reddit/test_subreddit.py
Labels: Feature

#1259 Address #1115
  praw/models/reddit/mixins/__init__.py
Labels: Documentation

#1161 Remove unicode string indicatiors
  CHANGES.rst
  praw/exceptions.py
  tests/integration/models/reddit/test_widgets.py
  tests/unit/test_exceptions.py
Labels: Delay until next release

#1319 Remove modaction
  CHANGES.rst
  praw/const.py
  praw/models/modaction.py
  tests/unit/test_deprecations.py
Labels: Delay until next release, Feature

#1320 Add method to retrieve friend data from users.friends
  CHANGES.rst
  praw/models/user.py
  tests/integration/cassettes/TestUser.test_friend_exist.json
  tests/integration/cassettes/TestUser.test_friend_not_exist.json
  tests/integration/models/test_user.py
Labels: Feature

#1324 Add code examples
  praw/models/listing/mixins/gilded.py
  praw/models/listing/mixins/rising.py
  praw/models/reddit/mixins/replyable.py
  praw/models/reddit/multi.py
  praw/models/reddit/subreddit.py
  praw/models/reddit/wikipage.py
Labels: Documentation

#1326 Document cached properties
  praw/models/reddit/collections.py
  praw/models/reddit/comment.py
  praw/models/reddit/submission.py
  praw/models/reddit/subreddit.py
  praw/models/reddit/wikipage.py
Labels: Documentation

#1302 Sub mod flair
  CHANGES.rst
  praw/models/reddit/submission.py
  tests/integration/cassettes/TestSubmissionModeration.test_flair_all.json
  tests/integration/cassettes/TestSubmissionModeration.test_flair_just_css_class.json
  tests/integration/cassettes/TestSubmissionModeration.test_flair_just_template_id.json
  tests/integration/cassettes/TestSubmissionModeration.test_flair_text_and_css_class.json
  tests/integration/cassettes/TestSubmissionModeration.test_flair_text_only.json
  tests/integration/cassettes/TestSubmissionModeration.test_flair_with_template_id.json
  tests/integration/models/reddit/test_submission.py
Labels: Feature
