Repository praw-dev/praw, pull requests merged in 2021-11, with the labels that each got.

#1808 Update awards table
  docs/code_overview/models/awards.txt
Labels: Documentation

#1805 Fix typo in CommentForrest docs
  praw/models/comment_forest.py
Labels: Documentation

#1794 Add clarification for `ratelimit_seconds` in the docs
  docs/getting_started/configuration/options.rst
  docs/getting_started/ratelimits.rst
  docs/index.rst
Labels: Documentation

#1801 Fix drafts
  CHANGES.rst
  praw/models/helpers.py
  praw/models/reddit/draft.py
  tests/integration/cassettes/TestDraft.test_submit__different_title.json
  tests/integration/models/reddit/test_draft.py
Labels: Bug, Documentation

#1810 Include *.png files
  setup.py
Labels: Developer Environment

#1802 Update GitHub files
  .github/CONTRIBUTING.md
  .github/CONTRIBUTING.rst
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/PULL_REQUEST_TEMPLATE.md
  docs/package_info/contributing.rst
Labels: Developer Environment

#1818 Add pre-commit badge
  README.rst
Labels: Documentation

#1799 Added Feature that allows users to pin submission on their profile
  AUTHORS.rst
  CHANGES.rst
  praw/models/user.py
  tests/integration/cassettes/TestUser.test_pin.json
  tests/integration/cassettes/TestUser.test_pin__comment.json
  tests/integration/cassettes/TestUser.test_pin__deleted_submission.json
  tests/integration/cassettes/TestUser.test_pin__empty_slot.json
  tests/integration/cassettes/TestUser.test_pin__ignore_conflicts.json
  tests/integration/cassettes/TestUser.test_pin__invalid_num.json
  tests/integration/cassettes/TestUser.test_pin__num.json
  tests/integration/cassettes/TestUser.test_pin__remove.json
  tests/integration/cassettes/TestUser.test_pin__remove_num.json
  tests/integration/cassettes/TestUser.test_pin__removed_submission.json
  tests/integration/cassettes/TestUser.test_pin__replace_slot.json
  tests/integration/models/test_user.py
Labels: Feature
