Repository praw-dev/praw, pull requests merged in 2021-06, with the labels that each got.

#1735 Add Redditor.trust, Redditor.distrust, and User.trusted
  CHANGES.rst
  praw/endpoints.py
  praw/models/reddit/redditor.py
  praw/models/user.py
  tests/integration/cassettes/TestRedditorListings.test_trust_and_distrust.json
  tests/integration/cassettes/TestRedditorListings.test_trust_blocked_user.json
  tests/integration/models/reddit/test_redditor.py
Labels: Feature

#1698 Add set_active_docs.py to set what versions are visible
  .github/workflows/set_active_versions.yml
  tools/set_active_docs.py
Labels: Developer Environment

#1743 Update CHANGES.rst
  CHANGES.rst
Labels: Documentation

#1675 Added submissions to attribute list in docs
  AUTHORS.rst
  praw/models/reddit/redditor.py
Labels: Documentation

#1739 Removed passive aggressive tone from quick start guide
  AUTHORS.rst
  docs/getting_started/quick_start.rst
Labels: Documentation

#1750 Fix set_active_docs.py
  tools/set_active_docs.py
Labels: Developer Environment

#1749 Add read_all_messages and unblock_subreddit
  CHANGES.rst
  docs/code_overview/other.rst
  docs/code_overview/other/fullnamemixin.rst
  docs/code_overview/other/inboxablemixin.rst
  praw/endpoints.py
  praw/models/inbox.py
  praw/models/reddit/mixins/inboxable.py
  tests/integration/cassettes/TestInbox.test_mark_all_read.json
  tests/integration/cassettes/TestMessage.test_unblock_subreddit.json
  tests/integration/models/reddit/test_message.py
  tests/integration/models/test_inbox.py
Labels: Feature
